[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python run_server.py"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
PORT = "8000"
