[build]
builder = "nixpacks"

[deploy]
startCommand = "python production_server.py"
healthcheckPath = "/api"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
RAILWAY_ENVIRONMENT = "production"
